const products = [
  {
    "id": "PRODMOBL0001",
    "image":
      "https://thetekcoffee.com/wp-content/uploads/2023/11/samsung-galaxy-s23-ultra-my.png",
    "name": "Galaxy S23 Ultra",
    "price": 1199.99,
    "brand": "Samsung",
    "description": "Flagship phone with advanced camera and S Pen support.",
    "rating": 4.8,
    "sizeScreen": 6.8,
  },
  {
    "id": "PRODMOBL0002",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-max-tim-thumb-600x600.jpg",
    "name": "iPhone 14 Pro Max",
    "price": 1099.99,
    "brand": "Apple",
    "description": "Premium iPhone with Dynamic Island and A16 Bionic chip.",
    "rating": 4.7,
    "sizeScreen": 6.7,
  },
  {
    "id": "PRODMOBL0003",
    "image":
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0yKvauCqHa8q9J3hKkgDHO2lPsxKJOD_qiA&s",
    "name": "Pixel 7 Pro",
    "price": 899.99,
    "brand": "Google",
    "description": "AI-powered phone with exceptional camera capabilities.",
    "rating": 4.6,
    "sizeScreen": 6.7,
  },
  {
    "id": "PRODMOBL0004",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/282903/xiaomi-13-pro-thumb-1-2-600x600.jpg",
    "name": "Xiaomi 13 Pro",
    "price": 999.99,
    "brand": "Xiaomi",
    "description": "High-performance phone with Leica-tuned cameras.",
    "rating": 4.5,
    "sizeScreen": 6.73,
  },
  {
    "id": "PRODMOBL0005",
    "image":
      "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/n/oneplus_11_-_black_-_rgb_1.jpg",
    "name": "OnePlus 11",
    "price": 799.99,
    "brand": "OnePlus",
    "description": "Fast and smooth phone with Hasselblad camera system.",
    "rating": 4.4,
    "sizeScreen": 6.7,
  },
  {
    "id": "PRODMOBL0006",
    "image":
      "https://cdn2.cellphones.com.vn/x/media/catalog/product/v/i/vivo-x90-pro.png",
    "name": "Vivo X90 Pro",
    "price": 849.99,
    "brand": "Vivo",
    "description": "Photography-focused phone with Zeiss optics.",
    "rating": 4.3,
    "sizeScreen": 6.78,
  },
  {
    "id": "PRODMOBL0007",
    "image":
      "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/f/i/findx5-pro.png",
    "name": "Oppo Find X5 Pro",
    "price": 999.99,
    "brand": "Oppo",
    "description": "Stylish phone with fast charging and great display.",
    "rating": 4.5,
    "sizeScreen": 6.7,
  },
  {
    "id": "PRODMOBL0008",
    "image":
      "https://product.hstatic.net/1000370129/product/ny-xperia-1-iv-white-digiphone_e2160b0a9b824af1ac1aab0003b77deb_master_7f7eb9e61a1d4e91ba766b3db9072961.jpg",
    "name": "Sony Xperia 1 IV",
    "price": 1299.99,
    "brand": "Sony",
    "description": "Creator-focused phone with 4K display and pro camera.",
    "rating": 4.2,
    "sizeScreen": 6.5,
  },
  {
    "id": "PRODMOBL0009",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/258167/realme-gt-2-pro-050122-080902-600x600.jpg",
    "name": "Realme GT2 Pro",
    "price": 749.99,
    "brand": "Realme",
    "description": "Affordable flagship with Snapdragon 8 Gen 1.",
    "rating": 4.3,
    "sizeScreen": 6.7,
  },
  {
    "id": "PRODMOBL0010",
    "image":
      "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/3/_/3_337_1.jpg",
    "name": "Asus ROG Phone 7",
    "price": 999.99,
    "brand": "Asus",
    "description": "Gaming phone with high refresh rate and powerful specs.",
    "rating": 4.6,
    "sizeScreen": 6.78,
  },
  {
    "id": "PRODMOBL0011",
    "image":
      "https://thetekcoffee.com/wp-content/uploads/2024/04/samsung-z-fold-5-1tb.webp",
    "name": "Galaxy Z Fold 5",
    "price": 1799.99,
    "brand": "Samsung",
    "description": "Foldable phone with multitasking capabilities.",
    "rating": 4.7,
    "sizeScreen": 7.6,
  },
  {
    "id": "PRODMOBL0012",
    "image":
      "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/1/5/15_2_7_2_5.jpg",
    "name": "iPhone 13 Mini",
    "price": 699.99,
    "brand": "Apple",
    "description": "Compact iPhone with A15 Bionic chip.",
    "rating": 4.5,
    "sizeScreen": 5.4,
  },
  {
    "id": "PRODMOBL0013",
    "image": "https://cdn2.cellphones.com.vn/x/media/catalog/product/6/g/6gg.jpg",
    "name": "Pixel 6a",
    "price": 449.99,
    "brand": "Google",
    "description": "Budget-friendly phone with Google Tensor chip.",
    "rating": 4.3,
    "sizeScreen": 6.1,
  },
  {
    "id": "PRODMOBL0014",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/299734/xiaomi-redmi-12-pro-4g-xanh-thumb-600x600.jpg",
    "name": "Redmi Note 12 Pro",
    "price": 399.99,
    "brand": "Xiaomi",
    "description": "Mid-range phone with great value and performance.",
    "rating": 4.2,
    "sizeScreen": 6.67,
  },
  {
    "id": "PRODMOBL0015",
    "image":
      "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/n/oneplus-nord-3_1_2.png",
    "name": "Nord 3",
    "price": 499.99,
    "brand": "OnePlus",
    "description": "Mid-range phone with fast charging and smooth display.",
    "rating": 4.4,
    "sizeScreen": 6.74,
  },
  {
    "id": "PRODMOBL0016",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/297025/vivo-v27-pro-1-600x600.jpg",
    "name": "Vivo V27 Pro",
    "price": 549.99,
    "brand": "Vivo",
    "description": "Stylish phone with curved AMOLED display.",
    "rating": 4.3,
    "sizeScreen": 6.78,
  },
  {
    "id": "PRODMOBL0017",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/260546/oppo-reno8-pro-thumb-xanh-1-600x600.jpg",
    "name": "Oppo Reno 8 Pro",
    "price": 599.99,
    "brand": "Oppo",
    "description": "Sleek phone with excellent selfie camera.",
    "rating": 4.2,
    "sizeScreen": 6.7,
  },
  {
    "id": "PRODMOBL0018",
    "image":
      "https://didongmango.com/images/products/2023/11/01/large/untitled-3_1698813681.jpg",
    "name": "Sony Xperia 5 IV",
    "price": 899.99,
    "brand": "Sony",
    "description": "Compact phone with pro-grade camera features.",
    "rating": 4.4,
    "sizeScreen": 6.1,
  },
  {
    "id": "PRODMOBL0019",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/309841/realme-narzo-60-5g-1-600x600.jpg",
    "name": "Realme Narzo 60",
    "price": 349.99,
    "brand": "Realme",
    "description": "Budget phone with solid performance.",
    "rating": 4.1,
    "sizeScreen": 6.6,
  },
  {
    "id": "PRODMOBL0020",
    "image":
      "https://cdn2.cellphones.com.vn/x/media/catalog/product/a/s/asus-zenfone-8-2021-premium-edition-global-dual-sim-td-lte-zs590ks-256gb-asus-s590-detailed-tech-specs_60b572a7f36d0.jpeg",
    "name": "Asus Zenfone 9",
    "price": 699.99,
    "brand": "Asus",
    "description": "Compact flagship with powerful performance.",
    "rating": 4.5,
    "sizeScreen": 5.9,
  },
  {
    "id": "PRODMOBL0021",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/303585/samsung-galaxy-a54-5g-tim-thumb-1-600x600.jpg",
    "name": "Galaxy A54",
    "price": 449.99,
    "brand": "Samsung",
    "description": "Mid-range phone with vibrant display.",
    "rating": 4.3,
    "sizeScreen": 6.4,
  },
  {
    "id": "PRODMOBL0022",
    "image":
      "https://bizweb.dktcdn.net/100/401/951/products/dac-diem-noi-bat-0427da37-4fe4-486f-92fc-9bdf61c6595e.png?v=1730111475323",
    "name": "iPhone SE (2022)",
    "price": 429.99,
    "brand": "Apple",
    "description": "Affordable iPhone with A15 Bionic chip.",
    "rating": 4.2,
    "sizeScreen": 4.7,
  },
  {
    "id": "PRODMOBL0023",
    "image":
      "https://cdn2.cellphones.com.vn/x/media/catalog/product/c/c/ccc_2_.jpg",
    "name": "Pixel 7a",
    "price": 499.99,
    "brand": "Google",
    "description": "Mid-range phone with excellent camera.",
    "rating": 4.4,
    "sizeScreen": 6.1,
  },
  {
    "id": "PRODMOBL0024",
    "image":
      "https://dienthoaihay.vn/images/products/2023/05/10/original/f5-xanh_1683709787.jpg.jpg",
    "name": "Poco F5",
    "price": 429.99,
    "brand": "Xiaomi",
    "description": "Performance-focused phone with Snapdragon 7+ Gen 2.",
    "rating": 4.3,
    "sizeScreen": 6.67,
  },
  {
    "id": "PRODMOBL0025",
    "image":
      "https://www.oneplus.com/content/dam/oasis/page/2023/global/product/larry/images-design-mo-img-3-1.jpg.webp",
    "name": "Nord CE 3 Lite",
    "price": 349.99,
    "brand": "OnePlus",
    "description": "Budget phone with 5G and fast charging.",
    "rating": 4.1,
    "sizeScreen": 6.72,
  },
  {
    "id": "PRODMOBL0026",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/302197/vivo-y100-xanh-thumb-1-600x600.jpg",
    "name": "Vivo Y100",
    "price": 299.99,
    "brand": "Vivo",
    "description": "Entry-level phone with stylish design.",
    "rating": 4.0,
    "sizeScreen": 6.38,
  },
  {
    "id": "PRODMOBL0027",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/309847/oppo-a78-xanh-thumb-1-600x600.jpg",
    "name": "Oppo A78",
    "price": 279.99,
    "brand": "Oppo",
    "description": "Affordable phone with AMOLED display.",
    "rating": 4.0,
    "sizeScreen": 6.43,
  },
  {
    "id": "PRODMOBL0028",
    "image":
      "https://cdn2.cellphones.com.vn/x/media/catalog/product/d/v/dvvd_4_.jpg",
    "name": "Sony Xperia 10 IV",
    "price": 499.99,
    "brand": "Sony",
    "description": "Mid-range phone with compact design.",
    "rating": 4.1,
    "sizeScreen": 6.0,
  },
  {
    "id": "PRODMOBL0029",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/301603/realme-c55-gold-1-750x500.jpg",
    "name": "Realme C55",
    "price": 199.99,
    "brand": "Realme",
    "description": "Budget phone with large display.",
    "rating": 3.9,
    "sizeScreen": 6.72,
  },
  {
    "id": "PRODMOBL0030",
    "image":
      "https://cdn.tgdd.vn/Files/2023/06/17/1534764/121-170623-225832-800-resize.jpg",
    "name": "Asus Zenfone 10",
    "price": 799.99,
    "brand": "Asus",
    "description": "Compact flagship with Snapdragon 8 Gen 2.",
    "rating": 4.5,
    "sizeScreen": 5.9,
  },
  {
    "id": "PRODMOBL0031",
    "image":
      "https://cdn2.fptshop.com.vn/unsafe/2024_3_28_638472353992099331_samsung-galaxy-zflip-5-xanh-ai.jpg",
    "name": "Galaxy Z Flip 5",
    "price": 999.99,
    "brand": "Samsung",
    "description": "Foldable phone with compact design.",
    "rating": 4.6,
    "sizeScreen": 6.7,
  },
  {
    "id": "PRODMOBL0032",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/240259/iPhone-14-plus-thumb-xanh-600x600.jpg",
    "name": "iPhone 14",
    "price": 799.99,
    "brand": "Apple",
    "description": "Mainstream iPhone with A15 Bionic chip.",
    "rating": 4.5,
    "sizeScreen": 6.1,
  },
  {
    "id": "PRODMOBL0033",
    "image":
      "https://mobileworld.com.vn/uploads/product/Pixel_8_series/thumbs/8a_mint_mbw.webp",
    "name": "Pixel 8",
    "price": 699.99,
    "brand": "Google",
    "description": "Latest Google phone with improved AI features.",
    "rating": 4.6,
    "sizeScreen": 6.2,
  },
  {
    "id": "PRODMOBL0034",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/279066/xiaomi-12t-pro-thumb-bac-1-600x600.jpg",
    "name": "Mi 12T Pro",
    "price": 749.99,
    "brand": "Xiaomi",
    "description": "High-performance phone with 200MP camera.",
    "rating": 4.4,
    "sizeScreen": 6.67,
  },
  {
    "id": "PRODMOBL0035",
    "image":
      "https://sonpixel.vn/wp-content/uploads/2024/07/oneplus-10t-Black.webp",
    "name": "OnePlus 10T",
    "price": 649.99,
    "brand": "OnePlus",
    "description": "Fast-charging phone with Snapdragon 8+ Gen 1.",
    "rating": 4.3,
    "sizeScreen": 6.7,
  },
  {
    "id": "PRODMOBL0036",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/253138/vivo-x80-xanh-thumb-600x600.jpg",
    "name": "Vivo X80",
    "price": 699.99,
    "brand": "Vivo",
    "description": "Premium phone with excellent camera system.",
    "rating": 4.4,
    "sizeScreen": 6.78,
  },
  {
    "id": "PRODMOBL0037",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/299034/oppo-find-n2-flip-purple-thumb-1-600x600-1-600x600.jpg",
    "name": "Oppo Find N2 Flip",
    "price": 899.99,
    "brand": "Oppo",
    "description": "Foldable phone with compact form factor.",
    "rating": 4.5,
    "sizeScreen": 6.8,
  },
  {
    "id": "PRODMOBL0038",
    "image":
      "https://product.hstatic.net/1000370129/product/xperia-1-v-mark-5-den_38ba7ebf4f71476f8251fcfa8ea82bbd_master.png",
    "name": "Sony Xperia 1 V",
    "price": 1399.99,
    "brand": "Sony",
    "description": "Flagship phone with 4K display and pro camera.",
    "rating": 4.3,
    "sizeScreen": 6.5,
  },
  {
    "id": "PRODMOBL0039",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/294514/realme-10-pro-thumb-600x600.jpg",
    "name": "Realme 10 Pro",
    "price": 349.99,
    "brand": "Realme",
    "description": "Mid-range phone with smooth display.",
    "rating": 4.2,
    "sizeScreen": 6.72,
  },
  {
    "id": "PRODMOBL0040",
    "image":
      "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/d/v/dvfdgty_1_.jpg",
    "name": "Asus ROG Phone 6",
    "price": 899.99,
    "brand": "Asus",
    "description": "Gaming phone with powerful cooling system.",
    "rating": 4.5,
    "sizeScreen": 6.78,
  },
  {
    "id": "PRODMOBL0041",
    "image":
      "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/s/m/sm-s908_galaxys22ultra_front_burgundy_211119_2_2_1.jpg",
    "name": "Galaxy S22",
    "price": 799.99,
    "brand": "Samsung",
    "description": "Compact flagship with great camera.",
    "rating": 4.4,
    "sizeScreen": 6.1,
  },
  {
    "id": "PRODMOBL0042",
    "image":
      "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/1/5/15_2_7_2_5.jpg",
    "name": "iPhone 13",
    "price": 699.99,
    "brand": "Apple",
    "description": "Reliable iPhone with A15 Bionic chip.",
    "rating": 4.5,
    "sizeScreen": 6.1,
  },
  {
    "id": "PRODMOBL0043",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/233009/google-pixel-6-600x600.jpg",
    "name": "Pixel 6",
    "price": 599.99,
    "brand": "Google",
    "description": "Affordable flagship with Google Tensor chip.",
    "rating": 4.3,
    "sizeScreen": 6.4,
  },
  {
    "id": "PRODMOBL0044",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/245261/Xiaomi-redmi-note-11-blue-600x600.jpg",
    "name": "Redmi Note 11",
    "price": 299.99,
    "brand": "Xiaomi",
    "description": "Budget phone with AMOLED display.",
    "rating": 4.1,
    "sizeScreen": 6.43,
  },
  {
    "id": "PRODMOBL0045",
    "image":
      "https://cellphones.com.vn/sforum/wp-content/uploads/2022/05/OnePlus-Nord-2T-cover.jpeg",
    "name": "Nord 2T",
    "price": 399.99,
    "brand": "OnePlus",
    "description": "Mid-range phone with fast charging.",
    "rating": 4.2,
    "sizeScreen": 6.43,
  },
  {
    "id": "PRODMOBL0046",
    "image": "https://cdn.tgdd.vn/Products/Images/42/241350/vivo-y70-600x600.jpg",
    "name": "Vivo Y70",
    "price": 249.99,
    "brand": "Vivo",
    "description": "Entry-level phone with decent performance.",
    "rating": 3.9,
    "sizeScreen": 6.44,
  },
  {
    "id": "PRODMOBL0047",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/311354/oppo-a58-4g-green-thumb-600x600.jpg",
    "name": "Oppo A58",
    "price": 229.99,
    "brand": "Oppo",
    "description": "Budget phone with large battery.",
    "rating": 3.8,
    "sizeScreen": 6.56,
  },
  {
    "id": "PRODMOBL0048",
    "image":
      "https://didongmango.com/images/products/2024/05/18/large/untitled-2_1716027477.jpg",
    "name": "Sony Xperia 5 V",
    "price": 999.99,
    "brand": "Sony",
    "description": "Compact flagship with pro camera features.",
    "rating": 4.4,
    "sizeScreen": 6.1,
  },
  {
    "id": "PRODMOBL0049",
    "image":
      "https://cdn2.cellphones.com.vn/x/media/catalog/product/1/s/1sdcsc.jpg",
    "name": "Realme C33",
    "price": 179.99,
    "brand": "Realme",
    "description": "Entry-level phone with large display.",
    "rating": 3.7,
    "sizeScreen": 6.5,
  },
  {
    "id": "PRODMOBL0050",
    "image":
      "https://cdn.tgdd.vn/Products/Images/42/236139/asus-zenfone-8-600x600.jpg",
    "name": "Asus Zenfone 8",
    "price": 599.99,
    "brand": "Asus",
    "description": "Compact phone with Snapdragon 888.",
    "rating": 4.3,
    "sizeScreen": 5.9,
  },
];

module.exports = products;
