export const phones = [
  {
    id: 1,
    name: "iPhone 14 Pro Max",
    description: "Màn hình Super Retina XDR, chip A16 Bionic mạnh mẽ",
    image: "/iphone-14-pro-max.jpg",
    rating: 5,
    brand: "Apple",
    reviews: 320,
    price: 1199.99,
    discountPrice: 1099.99,
    discountPercent: 8,
    isSpecialOffer: true,
  },
  {
    id: 2,
    name: "iPhone 13 Mini",
    description: "Nhỏ gọn, chip A15 Bionic, camera sắc nét",
    image: "/iphone-13-mini.jpg",
    rating: 4.7,
    brand: "Apple",
    reviews: 250,
    price: 699.99,
    discountPrice: 649.99,
    discountPercent: 7,
    isSpecialOffer: false,
  },
  {
    id: 3,
    name: "Samsung Galaxy S23 Ultra",
    description: "Camera 200MP, màn hình Dynamic AMOLED 2X",
    image: "/samsung-s23-ultra.jpg",
    rating: 4.8,
    brand: "Samsung",
    reviews: 280,
    price: 1299.99,
    discountPrice: 1199.99,
    discountPercent: 8,
    isSpecialOffer: true,
  },
  {
    id: 4,
    name: "Samsung Galaxy Z Fold 4",
    description: "Màn hình gập, Snapdragon 8+ Gen 1",
    image: "/samsung-z-fold-4.jpg",
    rating: 4.6,
    brand: "Samsung",
    reviews: 150,
    price: 1799.99,
    discountPrice: 1599.99,
    discountPercent: 11,
    isSpecialOffer: false,
  },
  {
    id: 5,
    name: "Xiaomi 13 Pro",
    description: "Hệ thống camera Leica, chip Snapdragon 8 Gen 2",
    image: "/xiaomi-13-pro.jpg",
    rating: 4.5,
    brand: "Xiaomi",
    reviews: 190,
    price: 899.99,
    discountPrice: 799.99,
    discountPercent: 11,
    isSpecialOffer: true,
  },
  {
    id: 6,
    name: "Xiaomi Redmi Note 12 Pro",
    description: "Màn hình AMOLED 120Hz, sạc nhanh 67W",
    image: "/xiaomi-redmi-note-12-pro.jpg",
    rating: 4.4,
    brand: "Xiaomi",
    reviews: 200,
    price: 399.99,
    discountPrice: 349.99,
    discountPercent: 12,
    isSpecialOffer: false,
  },
  {
    id: 7,
    name: "Google Pixel 7 Pro",
    description: "Màn hình 120Hz, chip Google Tensor G2",
    image: "/pixel-7-pro.jpg",
    rating: 4.7,
    brand: "Google",
    reviews: 210,
    price: 899.99,
    discountPrice: 849.99,
    discountPercent: 6,
    isSpecialOffer: false,
  },
  {
    id: 8,
    name: "Google Pixel 6a",
    description: "Nhỏ gọn, pin bền, camera AI xuất sắc",
    image: "/pixel-6a.jpg",
    rating: 4.5,
    brand: "Google",
    reviews: 180,
    price: 449.99,
    discountPrice: 399.99,
    discountPercent: 11,
    isSpecialOffer: true,
  },
  {
    id: 9,
    name: "Oppo Find X5 Pro",
    description: "Camera Hasselblad, màn hình LTPO AMOLED 120Hz",
    image: "/oppo-find-x5-pro.jpg",
    rating: 4.6,
    brand: "Oppo",
    reviews: 160,
    price: 999.99,
    discountPrice: 949.99,
    discountPercent: 5,
    isSpecialOffer: true,
  },
  {
    id: 10,
    name: "Oppo Reno 8 Pro",
    description: "Màn hình AMOLED 120Hz, chip Dimensity 8100",
    image: "/oppo-reno-8-pro.jpg",
    rating: 4.3,
    brand: "Oppo",
    reviews: 140,
    price: 599.99,
    discountPrice: 549.99,
    discountPercent: 8,
    isSpecialOffer: false,
  },
  {
    id: 11,
    name: "Vivo X90 Pro+",
    description: "Camera ZEISS, màn hình AMOLED 120Hz",
    image: "/vivo-x90-pro.jpg",
    rating: 4.3,
    brand: "Vivo",
    reviews: 130,
    price: 1099.99,
    discountPrice: 999.99,
    discountPercent: 9,
    isSpecialOffer: false,
  },
  {
    id: 12,
    name: "OnePlus 11",
    description: "Chip Snapdragon 8 Gen 2, màn hình 120Hz",
    image: "/oneplus-11.jpg",
    rating: 4.4,
    brand: "OnePlus",
    reviews: 150,
    price: 799.99,
    discountPrice: 749.99,
    discountPercent: 6,
    isSpecialOffer: true,
  },
  {
    id: 13,
    name: "Realme GT Neo 5",
    description: "Sạc nhanh 240W, hiệu năng mạnh mẽ",
    image: "/realme-gt-neo5.jpg",
    rating: 4.2,
    brand: "Realme",
    reviews: 120,
    price: 599.99,
    discountPrice: 549.99,
    discountPercent: 8,
    isSpecialOffer: false,
  },
  {
    id: 14,
    name: "Asus ROG Phone 6",
    description: "Điện thoại gaming với màn hình 165Hz",
    image: "/asus-rog-phone-6.jpg",
    rating: 4.8,
    brand: "Asus",
    reviews: 180,
    price: 1099.99,
    discountPrice: 999.99,
    discountPercent: 9,
    isSpecialOffer: true,
  },
  {
    id: 15,
    name: "Motorola Edge 30 Ultra",
    description: "Camera 200MP, Snapdragon 8+ Gen 1",
    image: "/motorola-edge-30-ultra.jpg",
    rating: 4.5,
    brand: "Motorola",
    reviews: 100,
    price: 899.99,
    discountPrice: 849.99,
    discountPercent: 6,
    isSpecialOffer: false,
  },
  {
    id: 16,
    name: "iPhone SE 2022",
    description: "Nhỏ gọn, chip A15 Bionic, giá hợp lý",
    image: "/iphone-se-2022.jpg",
    rating: 4.4,
    brand: "Apple",
    reviews: 210,
    price: 429.99,
    discountPrice: 399.99,
    discountPercent: 7,
    isSpecialOffer: true,
  },
  {
    id: 17,
    name: "Samsung Galaxy A54",
    description: "Màn hình Super AMOLED 120Hz, pin 5000mAh",
    image: "/samsung-a54.jpeg",
    rating: 4.2,
    brand: "Samsung",
    reviews: 170,
    price: 499.99,
    discountPrice: 449.99,
    discountPercent: 10,
    isSpecialOffer: false,
  },
  {
    id: 18,
    name: "OnePlus Nord 2T",
    description: "Dimensity 1300, màn hình AMOLED 90Hz",
    image: "/oneplus-nord-2t.jpg",
    rating: 4.3,
    brand: "OnePlus",
    reviews: 140,
    price: 499.99,
    discountPrice: 449.99,
    discountPercent: 10,
    isSpecialOffer: false,
  },
  {
    id: 19,
    name: "Realme 10 Pro+",
    description: "Màn hình cong 120Hz, Dimensity 920",
    image: "/realme-10-pro-plus.jpg",
    rating: 4.4,
    brand: "Realme",
    reviews: 160,
    price: 399.99,
    discountPrice: 369.99,
    discountPercent: 8,
    isSpecialOffer: true,
  },
  {
    id: 20,
    name: "Motorola G82",
    description: "Màn hình OLED 120Hz, pin 5000mAh",
    image: "/motorola-g82.jpg",
    rating: 4.2,
    brand: "Motorola",
    reviews: 110,
    price: 349.99,
    discountPrice: 299.99,
    discountPercent: 14,
    isSpecialOffer: false,
  },
  {
    id: 21,
    name: "iPhone 15",
    description: "Chip A17 Pro, thiết kế titan cao cấp",
    image: "/iphone-15.png",
    rating: 4.9,
    brand: "Apple",
    reviews: 300,
    price: 999.99,
    discountPrice: 949.99,
    discountPercent: 5,
    isSpecialOffer: true,
  },
  {
    id: 22,
    name: "Samsung Galaxy Z Flip 5",
    description: "Thiết kế gập thời thượng, màn hình 120Hz",
    image: "/samsung-z-flip-5.jpg",
    rating: 4.7,
    brand: "Samsung",
    reviews: 200,
    price: 1099.99,
    discountPrice: 999.99,
    discountPercent: 9,
    isSpecialOffer: false,
  },
  {
    id: 23,
    name: "Xiaomi 14",
    description: "Snapdragon 8 Gen 3, camera Leica cải tiến",
    image: "/xiaomi-14.png",
    rating: 4.6,
    brand: "Xiaomi",
    reviews: 220,
    price: 999.99,
    discountPrice: 899.99,
    discountPercent: 10,
    isSpecialOffer: true,
  },
  {
    id: 24,
    name: "Google Pixel 8",
    description: "Chip Tensor G3, AI nâng cao",
    image: "/pixel-8.jpg",
    rating: 4.8,
    brand: "Google",
    reviews: 230,
    price: 799.99,
    discountPrice: 749.99,
    discountPercent: 6,
    isSpecialOffer: false,
  },
  {
    id: 25,
    name: "Oppo Find N3",
    description: "Điện thoại gập, màn hình AMOLED 120Hz",
    image: "/oppo-find-n3.jpg",
    rating: 4.7,
    brand: "Oppo",
    reviews: 170,
    price: 1499.99,
    discountPrice: 1399.99,
    discountPercent: 7,
    isSpecialOffer: true,
  },
  {
    id: 26,
    name: "Vivo V29",
    description: "Camera selfie 50MP, thiết kế mỏng nhẹ",
    image: "/vivo-v29.jpg",
    rating: 4.4,
    brand: "Vivo",
    reviews: 140,
    price: 499.99,
    discountPrice: 449.99,
    discountPercent: 10,
    isSpecialOffer: false,
  },
  {
    id: 27,
    name: "OnePlus 12",
    description: "Snapdragon 8 Gen 3, sạc nhanh 100W",
    image: "/oneplus-12.jpg",
    rating: 4.5,
    brand: "OnePlus",
    reviews: 180,
    price: 899.99,
    discountPrice: 849.99,
    discountPercent: 6,
    isSpecialOffer: true,
  },
  {
    id: 28,
    name: "Realme Narzo 70 Pro",
    description: "Dimensity 7050, màn hình 120Hz",
    image: "/realme-narzo-70-pro.jpeg",
    rating: 4.3,
    brand: "Realme",
    reviews: 130,
    price: 349.99,
    discountPrice: 319.99,
    discountPercent: 9,
    isSpecialOffer: false,
  },
  {
    id: 29,
    name: "Asus Zenfone 10",
    description: "Nhỏ gọn, Snapdragon 8 Gen 2",
    image: "/asus-zenfone-10.jpg",
    rating: 4.6,
    brand: "Asus",
    reviews: 150,
    price: 799.99,
    discountPrice: 749.99,
    discountPercent: 6,
    isSpecialOffer: true,
  },
  {
    id: 30,
    name: "Motorola Razr 40",
    description: "Thiết kế gập cổ điển, màn hình 144Hz",
    image: "/motorola-razr-40.png",
    rating: 4.5,
    brand: "Motorola",
    reviews: 120,
    price: 999.99,
    discountPrice: 899.99,
    discountPercent: 10,
    isSpecialOffer: false,
  },
];